env: bali

podLabels:
  name: myname
  business_unit: agglayer
  role: myrole
  partner: Polygon
  network: mynetwork

existingSecret: op-secrets

schedule: "0 * * * *" # Run every hour
concurrencyPolicy: Forbid
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 1
backoffLimit: 1

config:
  l1:
    bridgeAddress: "0x123"
    gasTokenAddress: "0x123"

  l2:
    destinationAddress: "0x123"
    networkId: 123
