{{- if .Values.httpRoute.create -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "immutable-geth.fullname" . }}
spec:
  parentRefs:
    - kind: Gateway
      {{- with .Values.httpRoute.parentRef }}
      name: {{ .name }}
      namespace: {{ .namespace }}
      {{- end }}
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: {{ include "immutable-geth.fullname" . }}
          port: {{ .Values.service.http.port }}
{{- end }}
