apiVersion: v1
kind: Service
metadata:
  name: {{ include "immutable-geth.fullname" . }}
  labels:
    {{- include "immutable-geth.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  # StatefulSets require headless services
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "immutable-geth.selectorLabels" . | nindent 4 }}
