{{- if .Values.httpRoutes.aggsenderValidator.create -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "aggkit.fullname" . }}-aggsender-validator
spec:
  parentRefs:
    - kind: Gateway
      {{- with .Values.httpRoutes.aggsenderValidator.parentRef }}
      name: {{ .name }}
      namespace: {{ .namespace }}
      {{- end }}
  hostnames:
    - {{ .Values.httpRoutes.aggsenderValidator.hostname }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: {{ include "aggkit.fullname" . }}
          port: {{ .Values.container.ports.validator }}
{{- end }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "aggkit.fullname" . }}-health
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 5
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.container.ports.prometheus }}
        requestPath: /metrics
  targetRef:
    group: ""
    kind: Service
    name: {{ include "aggkit.fullname" . }}
