{{- if .Values.httpRoutes.aggsenderValidator.create -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "aggkit.fullname" . }}-aggsender-validator
spec:
  parentRefs:
    - kind: Gateway
      {{- with .Values.httpRoutes.aggsenderValidator.parentRef }}
      name: {{ .name }}
      namespace: {{ .namespace }}
      {{- end }}
  hostnames:
    - {{ .Values.httpRoutes.aggsenderValidator.hostname }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: {{ include "aggkit.fullname" . }}
          port: {{ .Values.container.ports.validator }}
{{- end }}
