{{- if .Values.httpRoutes.aggsenderValidator.create -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "aggkit.fullname" . }}-aggsender-validator
  labels:
    {{- include "aggkit.labels" . | nindent 4 }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.httpRoutes.aggsenderValidator.parentRef.name }}
      namespace: {{ .Values.httpRoutes.aggsenderValidator.parentRef.namespace }}
  hostnames:
    - "{{ .Values.httpRoutes.aggsenderValidator.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "aggkit.fullname" . }}
          port: {{ .Values.container.ports.validator }}
{{- end }}
