apiVersion: v1
kind: Service
metadata:
  name: {{ include "aggkit.fullname" . }}
  labels:
    {{- include "aggkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.container.ports.aggsender }}
      targetPort: aggsender
      protocol: TCP
      name: aggsender
    - port: {{ .Values.container.ports.bridge }}
      targetPort: bridge
      protocol: TCP
      name: bridge
    - port: {{ .Values.container.ports.validator }}
      targetPort: validator
      protocol: TCP
      name: validator
      appProtocol: kubernetes.io/h2c
    {{- if .Values.config.prometheus.enabled }}
    - port: {{ .Values.container.ports.prometheus }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
    {{- end }}
  # StatefulSets require headless services
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "aggkit.selectorLabels" . | nindent 4 }}
