apiVersion: v1
kind: Service
metadata:
  name: {{ include "aggkit.fullname" . }}
  labels:
    {{- include "aggkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.container.ports.aggsender }}
      targetPort: aggsender
      protocol: TCP
      name: aggsender
    - port: {{ .Values.container.ports.bridge }}
      targetPort: bridge
      protocol: TCP
      name: bridge
    - port: {{ .Values.container.ports.validator }}
      targetPort: validator
      protocol: TCP
      name: validator
      appProtocol: kubernetes.io/h2c
    - port: {{ .Values.container.ports.prometheus }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  # StatefulSets require headless services
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "aggkit.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "aggkit.fullname" . }}-health
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 5
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.container.ports.prometheus }}
        requestPath: /metrics
  targetRef:
    group: ""
    kind: Service
    name: {{ include "aggkit.fullname" . }}
