apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aggkit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggkit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "aggkit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.config.prometheus.enabled }}
        ad.datadoghq.com/{{ .Chart.Name }}.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:{{ .Values.container.ports.prometheus }}/metrics",
                  "namespace": "aggkit",
                  "metrics": ["^aggsender_.*", "^aggoracle_.*", "^bridge_.*"]
                }
              ]
            }
          }
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aggkit.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "aggkit.serviceAccountName" . }}
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
        - {{ toYaml $constraint | nindent 10 | trim }}
            {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              {{- include "aggkit.selectorLabels" $ | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command:
            - aggkit
          args:
            - run
            - --cfg=/etc/aggkit/config.toml
            - --components={{ .Values.config.components | join "," }}
          ports:
            - name: aggsender
              containerPort: {{ .Values.container.ports.aggsender }}
              protocol: TCP
            - name: bridge
              containerPort: {{ .Values.container.ports.bridge }}
              protocol: TCP
            - name: validator
              containerPort: {{ .Values.container.ports.validator }}
              protocol: TCP
            {{- if .Values.config.prometheus.enabled }}
            - name: prometheus
              containerPort: {{ .Values.container.ports.prometheus }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.container.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.mountRawConfig }}
            - mountPath: "/etc/aggkit"
              name: config
              readOnly: true
            {{- end }}
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
      volumes:
        {{- with .Values.extraVolumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.mountRawConfig }}
        - name: config
          projected:
            sources:
            - configMap:
                name: {{ include "aggkit.fullname" . }}
                items:
                  - key: "config.toml"
                    path: "config.toml"
            - secret:
                name: op-secrets
                items:
                  {{- if and (has "aggsender" .Values.config.components) (eq .Values.config.aggsender.privateKey.keyName "") }}
                  - key: {{ .Values.config.aggsender.privateKey.keystoreFileName }}
                    path: {{ .Values.config.aggsender.privateKey.keystoreFileName }}
                  {{- end }}
                  {{- if and (has "aggsender-validator" .Values.config.components) (eq .Values.config.aggsenderValidator.privateKey.keyName "") }}
                  - key: {{ .Values.config.aggsenderValidator.privateKey.keystoreFileName }}
                    path: {{ .Values.config.aggsenderValidator.privateKey.keystoreFileName }}
                  {{- end }}
                  {{- if and (has "aggoracle" .Values.config.components) (eq .Values.config.aggoracle.privateKey.keyName "") }}
                  - key: {{ .Values.config.aggoracle.privateKey.keystoreFileName }}
                    path: {{ .Values.config.aggoracle.privateKey.keystoreFileName }}
                  {{- end }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- with .Values.storage.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
