replicaCount: 1

config:
  network: testnet # options: testnet, mainnet
  extraArgs: []

image:
  repository: ghcr.io/immutable/immutable-geth/immutable-geth
  pullPolicy: IfNotPresent
  tag: "v1.0.0-beta.16"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

storage:
  path: /data
  size: 500Gi

service:
  type: ClusterIP
  http:
    port: 8545
  annotations: {}

ingress:
  create: false
  hostname: something.dev.polygon

httpRoute:
  create: false
  hostname: immutable-geth.development.polygon.internal
  parentRef:
    name: development-polygon-internal
    namespace: gateways

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
